hypothesis/browser-extension

Makefile
package.json
settings/chrome-dev.json
settings/chrome-prod.json
settings/firefox-dev.json
settings/firefox-prod.json
tools/settings.js

This commit sets up the build to automatically generate a sensible version number and version name on the basis of:
- the latest git tag, which is assumed to reflect the version of the underlying client
- the number of commits since that tag
- whether or not the build is a 'production' build

Automatically generate a sensible extension version number

---

settings/chrome-dev.json

By default a dev install of bouncer runs at http://localhost:8000/.
Even if you've correctly configured bouncer with your dev Chrome
extension ID in an environment variable, your dev bouncer links won't
work (they'll redirect to Via instead of to your dev Chrome extension)
unless your dev Chrome extension is also configured with your dev
bouncer URL.
We used to be able to do this with the --bouncer arg to the
hypothesis-buildext command.
With this new Makefile for building the Chrome extension, it seems
better for a dev Chrome extensions to work with a dev bouncer (running
at the default dev bouncer URL) than to not work with any bouncer at
all.

Make dev bouncer work with dev Chrome extension

---

.eslintignore
.eslintrc
Makefile
package.json
src/chrome/help/index.js
src/chrome/lib/destroy.js
src/common/browser-action.js
src/common/detect-content-type.js
src/common/hypothesis-chrome-extension.js
src/common/install.js
src/common/sidebar-injector.js
src/common/tab-state.js
src/common/uri-info.js
tests/bootstrap.js
tests/common/browser-action-test.js
tests/common/errors-test.js
tests/common/help-page-test.js
tests/common/hypothesis-chrome-extension-test.js
tests/common/sidebar-injector-test.js
tests/common/tab-state-test.js
tests/common/tab-store-test.js
tests/common/uri-info-test.js
tests/karma.config.js
tools/.eslintrc
tools/settings.js
tools/template-context-app.js
tools/template-context-settings.js

This sets up ESLint using the same shared config as the `client` and `h` repos.
There are three commits in this PR:
- The first adds the ESLint config and a `make lint` task
- The second fixes up trivial issues using `eslint . --fix`
- The third includes manual fixes for the remaining issues, which included several missing function returns, missing or misplaced 'use strict' and parenthesis in the wrong place in a function call

Setup ESLint using shared config

---

tools/release-it

It serves mostly as documentation for the current release process and a reference for when we come to automate the process entirely in future.

Add a script that creates and pushes a new tag

---

tests/common/tab-store-test.js

The current version of sinon reported an error due to incorrect use of `assert.called()` instead of `assert.calledWith()`

Fix incorrect use assert.called()

---

.travis.yml

This keeps things consistent with the version of Node used by h:
https://github.com/hypothesis/h/commit/cc71f6c571829344e1f50a05b33504a2d42725d4

Use Node v6.2 on Travis

---

src/common/hypothesis-chrome-extension.js
src/common/install.js
tests/common/hypothesis-chrome-extension-test.js
tests/common/install-test.js

Use the service URL from the extension's settings to construct the URL
for the '/welcome' page and the URL pattern that allows requests made by
the extension to set cookies for the Hypothesis domain.
Previously both of these were hardcoded to 'https://hypothes.is', an
issue that was noticed when testing deployment of the service to
Skyliner under a different domain.
----
Manual testing:
1. Remove the existing unpacked extension (if any) locally
2. Change the domain for the extension in `settings/chrome-prod.json` to a different domain (eg. 'https://next.hypothes.is/' - note the empty '/' path here is part of the service URL) and build the extension for production.
3. Re-add the unpacked extension and verify that after installation, a tab is opened at `<service domain>welcome`

Use service URL from settings to construct welcome page URL

---

src/client/app.html.mustache

**This needs to be merged _before_ an extension containing https://github.com/hypothesis/client/pull/243 is released.**
https://github.com/hypothesis/client/pull/243 changes the client to use
the same class name, `js-hypothesis-config`, for config script tags in
both the sidebar app and host page.
This updates the extension's app.html template to use the expected name.

Update class name for config script tag in sidebar app

---

settings/chrome-stage.json
settings/firefox-stage.json

It makes more sense to deduplicate all errors in Sentry using a single DSN. The client knows its own version number, which makes tracking down the source of errors easier.

Unify the client's Sentry DSN

---

README.md

Add a couple of tips on using `npm link`. These come from <http://h.readthedocs.io/en/latest/developing/install/client/> which is going to be deleted

Add some npm link tips

---

.travis.yml
package.json
tools/chrome-webstore-refresh-token
tools/deploy

Use the [chrome-webstore-upload-cli](https://github.com/DrewML/chrome-webstore-upload-cli) tool to upload Chrome extensions to the Chrome Web Store automatically on pushes to master.
The stage extension is uploaded and published automatically. The prod extension is uploaded so the Chrome Web Store can start performing malware checks but not actually published. This gives us a chance to do any manual testing we want with the stage extension before hitting the Publish button in the Chrome Web Store's Developer Dashboard.
CHROME_WEBSTORE_{CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN} env vars have been added to the Travis CI config. Generating the refresh token is a PITA, so I have added a script to document and assist with the process if we ever need to do it again.

Automate upload of Chrome extensions to Chrome Web Store

---

package.json

Fix the `git push` command that `npm version` runs after making a new
version.
The command as it was assumed that the user's git repo's `origin` remote
is https://github.com/hypothesis/browser-extension, which is not always
the case. For example it's common to fork an open source repo to another
github (or bitbucket etc) account and then clone your own fork locally.

Fix postversion git push command

---

tools/update-client

The docs for releasing a Chrome extension say to checkout and pull the
latest master branch manually.
The script as its currently written assumes that the user's master
branch is setup as a tracking branch of the hypothesis organization's
master branch on GitHub, which while a common setup isn't always the
case (it's not the case for me, for example, so the script crashes for me).
For example it's common to fork a github repo and then clone your fork.

Don't do git checkout or pull from a script

---

.babelrc
Makefile
package-lock.json
package.json
tests/karma.config.js

Enable use of ES6 language features using Babelify.
Since the code in this repository only needs to target reasonably recent
versions of Chrome and Firefox, use [babel-preset-env](https://github.com/babel/babel-preset-env) to control which
ES6 => ES5 transformations are applied based on the browser versions we
want to support.
The versions are initially set conservatively to the minimum Firefox
version that has sufficiently complete WebExtensions support (48) and
Chrome circa ~2 years ago. We can bump these in future when we get data
that gives us a better idea of what versions our users are actually
using.

Enable ES6 usage

---

Makefile
src/common/browser-name.js
src/common/help-page.js
src/common/hypothesis-chrome-extension.js
tests/common/help-page-test.js
tests/common/hypothesis-chrome-extension-test.js

This is a set of three fixes for the Firefox WebExtension which, together with https://github.com/hypothesis/client/pull/460 , enables the extension to work in the current stable version of Firefox (v51).
See individual commit messages for details.
**Steps to test:**
1. Checkout https://github.com/hypothesis/client/pull/460 in the client repo and build the client.
2. Checkout this PR in the browser-extension repo
3. Build the Firefox dev extension `make SETTINGS_FILE=settings/firefox-dev.json`, making sure that you are using the client build from (1)
4. In the stable version of Firefox, go to "about:debugging#addons", click "Load Temporary Addon" and select the "manifest.json" file from the "build" directory.

Fix client failing to load in Firefox WebExtension

---

package-lock.json
package.json
src/chrome/manifest.json.mustache
tools/deploy

This PR adds signing of the Firefox extension using Mozilla's [web-ext](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext) CLI tool during builds on the master branch. Signing the builds enables them to be installed in stable releases of Firefox.
Since the deployment script doesn't run on the master, I tested this by modifying the `.travis.yml` config during development of this branch and using different extension IDs than are in this final PR. You can see the extensions that were built and uploaded from the earlier version of the branch in the [AMO Manage My Submissions](https://addons.mozilla.org/en-GB/developers/addons) console (See Passpack for credentials, ping me if you don't see them).
----
Once this is done, the remaining steps before being …

Sign Firefox extension during build

---

settings/chrome-prod.json
settings/chrome-stage.json
settings/firefox-prod.json
settings/firefox-stage.json
tools/template-context-app.js

This adds the OAuth client IDs registered at https://hypothes.is/admin/oauthclients to the browser extension config. OAuth is currently disabled but enabling it once everything else is ready will be a matter of flipping the "oauthEnabled" flag.
Note that this does not yet work for the stage and prod extensions when built locally because the extension IDs are currently different than when using an extension from the Chrome Web Store. You can work around this for testing purposes by copying the "key" entry from `~/Library/Application Support/Google/Chrome/Default/Extensions/{extension ID}/{version}/manifest.json` into `src/chrome/manifest.json.mustache`. This will cause the locally built extension to have the same ID as the extension downloaded from the Chrome web store.
I think we'll …

Add OAuth configuration to extension settings

---

src/chrome/manifest.json.mustache
src/common/install.js
tests/common/install-test.js

As of v1.39, the Hypothesis client detects when third party cookies are
blocked and will use OAuth rather than cookie authentication in that
case. Therefore, we can stop asking for the "contentSettings" permission which produces a scary warning (see hypothesis/browser-extension#46) and remove the code that modifies these browser settings.
There is a potential issue in that the detection of cookie blocking checks reading/writing cookies against the browser extension's domain (`chrome-extension://{id}`) whereas the actual cookies are set for the hypothes.is domain. However, the "block third party cookies" setting in Safari, Firefox and Chrome treats both as third party cookies and so the "can I set cookies" check that the client works as expected.
Fixes hypothesis/browser-extension#46
Fixes …

Stop adding h domain to cookie whitelist during install

---

settings/chrome-prod.json
settings/chrome-stage.json
settings/firefox-prod.json
settings/firefox-stage.json

Previously OAuth was only used in the browser extensions if third-party cookies were blocked. This PR enables it as the authentication method for all users.

Enable OAuth in the browser extensions

---

docs/building.md
settings/chrome-prod.json
settings/chrome-stage.json
src/chrome/manifest.json.mustache

_Context: I'm currently updating the client's [development docs](http://h-client.readthedocs.io/en/latest/developers/developing/#setting-up-a-client-development-environment) and addressing the fact that the [running from a browser extension](http://h-client.readthedocs.io/en/latest/developers/developing/#running-the-client-from-the-browser-extension) steps don't "just work" after the OAuth changes_.
----
By default, locally built Chrome extensions get system-dependent IDs which differ from the IDs that are assigned when the extension is published in the Chrome Web Store. The IDs are part of the URLs of the extension's assets (`chrome-extension://{ID}/{path}`), including the url of the sidebar app (`/client/app.html`) which makes the request to the h service's authorization endpoint.
This …

Use fixed IDs for locally built stage and prod extensions

---

.travis.yml

The current version of `web-ext` depends on Node >= v6.3 or later due to
use of `fs.constants`.
This commit configures Travis to use the current LTS release of Node (v8.x),
which should hopefully always be current enough without running into
occassional issues with dependencies that sometimes happen when a new
stable Node release (currently v9.x) comes out.
This should fix this deployment failure: https://travis-ci.org/hypothesis/browser-extension/builds/369061182

Update Node version on Travis

---

.travis.yml

By default Travis runs `npm install`. This can end up modifying
`package-lock.json` if Travis has a different version of npm than
whoever committed the last changes to the lockfile.
`npm ci` should avoid this problem by installing _only_ from the
lockfile. This command also promises faster installation. Since this
command was introduced in npm v5.7, we need to first install a newer
version of npm.
- Change the cache directory as per the `npm ci` docs.

Use `npm ci` to install dependencies

---

src/chrome/manifest.json.mustache

These keys appear to not work in Firefox.

Guard more manifest keys that as Chrome-only

---

Makefile

Appending this token to the end of `boot.js` causes a syntax error with the
latest version of the client since the structure of the code changed.
Additionally the hack does not appear to be required any more (tested with Firefox 64).
This reverts commit 2674d22cbfda70627ba225f99af815a457f1ab19.

Revert "Make return value of boot script serializable"

---

src/common/direct-link-query.js
src/common/hypothesis-chrome-extension.js
tests/common/direct-link-query-test.js
tests/common/hypothesis-chrome-extension-test.js

Support the `#annotations:group:<ID>` syntax used to direct-link to
groups.
As part of this, refactor the code so that the knowledge about the
different kinds of direct-link query that can be used only exists in
one place, `direct-link-query.js`, which is responsible for mapping the
query to additional client configuration.
Also add some comments about why the browser extension has to deal with
direct-links itself in the first place.
----
To make it harder to overlook this in future if we change the direct linking syntax again, we could rework the overall flow as follows:
1. User navigates to $BOUNCER_URL/$QUERY
2. Bouncer detects the extension and sends it a message indicating the URL to open in the current tab and additional client configuration to pass to the client
3. The browser …

Support direct links to groups

---

settings/chrome-prod.json
settings/chrome-stage.json
settings/firefox-prod.json
settings/firefox-stage.json
tools/template-context-app.js

This flag has not been used in the client since Nov 2017
(see https://github.com/hypothesis/client/commit/493c21a62ca1cc86e107356c87eb6839f43ca4fd)

Remove "oauthEnabled" flag

---

docs/building.md

Docs did not detail this step which is critical for local development when hosting your own instance of h.

Add note about OAuthClientID to docs

---

src/common/detect-content-type.js
tests/common/detect-content-type-test.js

Chrome recently made changes to how the native PDF viewer is loaded [1],
which slightly changes the HTML of the top-level document in tabs that
are using this viewer. Specifically, the `<embed>` element no longer has a
`name` attribute. This broke the browser extension's detection of
whether the current document is a PDF by checking whether Chrome is
using its native PDF viewer to show it [2].
Resolve the issue by adjusting the CSS selector slightly.
To test, verify that activating the extension on a PDF uses the bundled
PDF.js viewer both when the "MimeHandlerViewer in cross-process frame"
feature flag in Chrome is turned on (at chrome://flags) and when it is
turned off.
Fixes #212
[1] https://bugs.chromium.org/p/chromium/issues/detail?id=659750
[2] nb. We use this method rather than …

Fix detection of whether a tab is using Chrome's PDF viewer

---

src/chrome/manifest.json.mustache

Remove a reference to a client script bundle from the background page.
The name of the bundle changed in the client to `sentry.bundle.js` and
now contains different packages.
The browser extension should not depend on the package structure of the
client, so simply remove this dependency from the background page. If
the background page wants to use Sentry, it should use its own copy of
the code.
I'm not entirely clear on why this dependency was added in the first
place. It was not explained in the commit
(a3a48770ae1fd5ed65e1fdbc0a974699e1c1e800) that added it.

Remove reference to raven-js.bundle.js from background page manifest

---

src/chrome/manifest.json.mustache

Firefox's extension validation service is producing many warnings
complaining about APIs that are unsupported in Firefox v48 [1]. Since the FF
extension doesn't have active users at the moment, there is no harm in
bumping the minimum version to the current Firefox ESR release (v60).
[1] See eg. https://addons.mozilla.org/en-US/developers/upload/5efc192fadf74767bfe9735e006e3f0d

Bump minimum Firefox version

---

src/sidebar-app.html.mustache

The related client change was deployed a long time ago.

Remove an obsolete class from config script tag

---

docs/building.md

I could not find this step in our docs anywhere but I think its important (or at least makes sense) to including in the building.md file.

Make it clear the browser ext needs its own oauth ID value

---

src/help/index.html
src/options/index.html
src/sidebar-app.html.mustache

Specify the language of the sidebar HTML page and the extension's Help
and Options pages. This helps screen readers choose an appropriate voice
to read the UI amongst other things.
This is currently always English.
See also https://github.com/hypothesis/h/pull/5906.
Part of https://github.com/hypothesis/client/issues/1794.

Specify language of sidebar, Help and Options pages

---

Dockerfile
Jenkinsfile
tests/karma.config.js

This is part of https://github.com/hypothesis/browser-extension/issues/247.
As part of automating more of the process of building and deploying the extension, including the process of updating the extension when a new build of the Hypothesis client is released, create a Jenkins build for the extension. This mostly involved following the relevant parts of [our documentation for adding a new Jenkins project](https://github.com/hypothesis/playbook/blob/master/docs/deploying-a-new-app.md#add-a-jenkinsfile-to-your-app-for-continuous-integration) and copying / adapting relevant files from the client repository.
This PR only implements the steps to run tests and build the extension zip archives which are run for all PRs. Moving the deployment for builds on the master branch from Travis to …

Add Jenkins build/test

---

package-lock.json

This PR is the result of updating all non-top-level dependencies to
current compatible versions by running:
```
rm package-lock.json
npm install
```
...and committing the newly-generated package-lock.json.
This fixes a bunch of compile errors when running `npm install` due to
an outated version of fsevents.
Auditing every updated package manually is not really viable, so we're relying on `npm audit` and GitHub's security checks.

Regenerate lockfile to update dependencies

---

src/background/.eslintrc
src/background/browser-action.js
src/background/browser-name.js
src/background/detect-content-type.js
src/background/direct-link-query.js
src/background/errors.js
src/background/help-page.js
src/background/hypothesis-chrome-extension.js
src/background/index.js
src/background/install.js
src/background/raven.js
src/background/settings.js
src/background/sidebar-injector.js
src/background/tab-state.js
src/background/tab-store.js
src/background/uri-info.js
src/background/util.js
tests/background/.eslintrc
tests/background/browser-action-test.js
tests/background/detect-content-type-test.js
tests/background/direct-link-query-test.js
tests/background/errors-test.js
tests/background/help-page-test.js
tests/background/hypothesis-chrome-extension-test.js
tests/background/install-test.js
tests/background/sidebar-injector-test.js
tests/background/tab-state-test.js
tests/background/tab-store-test.js
tests/background/uri-info-test.js
tests/karma.config.js

For consistency with our other projects, modernize the background page sources, which constitute most of the extensions' code, to use ES modules. There are a few other single-file scripts which are used in different contexts and have been left alone as they don't import anything.
This mostly uses the same `convert-to-es-modules` conversion script from the hypothesis/frontend-toolkit repo that was used for the client. I had to apply some of the same fixes to the codebase (eg. hoisting imports to the top level) that were also applied in the client.

Convert background page to ES modules

---

.eslintignore
.travis.yml
Jenkinsfile
tools/deploy

As the next step in moving our browser extension deployment process from
Travis to Jenkins, move the extension upload and publish steps.
The credentials are listed under the [browser-extension project](https://jenkins.hypothes.is/job/browser-extension/credentials/store/folder/domain/_/).

Move extension deployment to Jenkins

---

src/help/index.html

FTP support is being removed from Chrome (see
https://www.ghacks.net/2019/08/16/google-chrome-82-wont-support-ftp-anymore/)
Also re-word the error message slightly to be clearer about the protocol
restriction.

Remove obsolete reference to FTP

---

.travis.yml
Jenkinsfile
settings/chrome-qa.json
settings/firefox-qa.json
src/background/browser-action.js
tests/background/browser-action-test.js
tools/deploy

We use the term "QA" rather than "staging" to refer to our
pre-production test environment for all other Hypothesis projects.
Rename the QA extension accordingly to avoid confusion.
- Rename all references to the "stage" extension to "QA" to refer
- Change the browser action label for the QA extension from "STG" to
"QA"
- Fix an invalid URL for the QA bouncer service

Rename "stage" extension to "QA"

---

tools/chrome-webstore-refresh-token

Update comments to reflect the fact that the resulting token needs to
be used in both Jenkins and Travis.

Update comments in chrome-webstore-refresh-token script

---

tools/deploy

Attempt to speed up the Firefox extension signing process by uploading
both extensions and waiting for signing to complete in parallel. To make
the deployment log output easier to read, the log output from each upload is
buffered into a file and then output at once after each upload
completes.
Also make the log output easier to read by filtering out progress
messages from `webext sign`, since the tool does not follow the usual
convention of suppressing progress bars when the output is a not an
interactive terminal.
On a maintenance note, I think the logic in the `tools/deploy` script is getting to the limit of what I would comfortably put in a shell script before switching to a "proper" programming language. If we find a need to make more additions, I would probably translate this to a …

Upload QA and prod Firefox extensions in parallel

---

src/sidebar-app.html.mustache

This is no longer used by the client as it doesn't use AngularJS for
routing or URL management any more.

Remove `<base>` tag from sidebar HTML template

---

src/background/direct-link-query.js
tests/background/direct-link-query-test.js

Unlike all groups with [randomly generated pubids](https://github.com/hypothesis/h/blob/6eb5dee986e3e786c095382e54a5ad2781dfbd42/h/pubid.py#L33), the public group's
pubid contains underscores, which caused the extension's URL fragment matching to fail.
There is a broader issue around whether the extension should have to know about the character set of various kinds of identifier or even all the possible syntaxes of an `#annotations:` fragment. For the moment, this PR just implements the minimal fix plus a test.
Fixes https://github.com/hypothesis/bouncer/issues/323

Activate extension when following direct link to public group

---

Jenkinsfile

Fix an issue where the Jenkins build could fail the "Upload Package"
step or attempt to upload packages from a previous build in this step.
This issue arose because the build used two separate `node` blocks and
the second `node` block assumed it was using the same workspace
directory with the same contents as the first `node` block.
The fix is just to use one `node` block for the whole build.
The only reason to use separate `node` blocks is to free up an executor
while awaiting manual approval for a deployment. We currently don't do
that at any point during an extension build, although we likely will if
we make it possible to deploy to prod from Jenkins rather than from the
Chrome Web Store developer dashboard.
If you want a fuller explanation of the general issue, please see the notes on …

Fix possible deploy from incorrect workspace

---

tests/karma.config.js

Apply the same fix as was used in the "client" repo in
https://github.com/hypothesis/client/pull/2086.

Fix test runner under Node 14

---

Makefile

Add a babelify transform to the command for generating the Makefile's
dependencies.
The dependencies list is incorrect otherwise, as the ES6 imports are not
correctly listed without babel-ifying first into `require` syntax.

Add babelify transform when generating build dependencies

---

docs/building.md

Try to rectify the slight chicken-and-egg confusion in building a development
extension.
Remove all instances of the word "simply" because of personal prejudice.

Clarify instructions for building local extension

---

tests/karma.config.js

Remove the `presets` override in `karma.config.js` and resolve an issue
that prevented configuration in the `.babelrc` file being used for
source files located outside of the `tests/` directory.
Using the same compilation settings ensures that the test environment
better matches the actual build. It also fixes a problem with using
async/await syntax and other modern JS syntax in tests / code being
tested.
Slack debugging thread: https://hypothes-is.slack.com/archives/D01AJ11PUER/p1603459022001600

Use same compilation settings in tests and bundle build

---

Jenkinsfile

When `npm` was replaced with `yarn`, the syntax for specifying the new
version needed to be updated.
See https://classic.yarnpkg.com/en/docs/cli/version/.

Correct `yarn version` syntax

---

src/background/tab-state.js
src/background/uri-info.js
tests/background/tab-state-test.js
tests/background/uri-info-test.js

It implements a custom debouncing mechanism.
A more standard approach like using `lodash._debounce` is not suited for
this particular case, because TabState is shared amoung all the tabs.
Reloading two tabs simulatneously shouldn't make one of the requests
to be cancelled.
The cancellation of a pending request could happen during the
waiting period or in-flight badge request.
Resolves #396

Reduce the number of badge requests

---

Makefile
package.json
src/background/browser-name.js
src/background/errors.js
src/background/help-page.js
src/background/index.js
src/background/install.js
src/background/raven.js
src/background/settings.js
src/background/sidebar-injector.js
src/background/tab-state.js
src/background/util.js
src/help/index.js
src/options/options.js
src/pdfjs-init.js
src/tsconfig.json
yarn.lock

This PR adds type checking to the browser-extension project in a similar manner to how we have it set up for the client and lms projects. It also fixes the small number of existing type checking errors.
This will help catch mistakes in JSDoc documentation, incorrect API usage etc.
To run type checking locally use `yarn typecheck` or `make lint`. If you have an editor integration set up already that should also flag errors.

Enable type checking

---

src/background/errors.js

Use ES classes to simplify the definition of custom error types in the
extension.
All of the custom constructors can be removed because derived classes automatically forward constructor arguments to their base class.

Simplify custom error definitions

---

src/background/errors.js
src/background/tab-state.js
tests/background/tab-state-test.js
tests/background/uri-info-test.js

If errors arise during the fetching of badge requests it reset the count to 0.
In case of cancellations, do not reset the count to 0.

Reset the badge count to 0 in case of badge fetch failures, not cancellation

---

src/background/errors.js
src/background/tab-state.js
src/background/uri-info.js
tests/background/tab-state-test.js
tests/background/uri-info-test.js

In order to further reduce the number of badge requests we implement a cache or badge request results. This cache is temporal and it contains key-value pairs of URLs and annotation counts.
* every entry in the cache (URL and annotation count pair) is added only after successful fetching of the annotation count.
* fragment is removed from the URL
* every entry in the cache  is stored for X amount of time. After that time the entry is deleted. This is to allow updating the annotation count in case of reloading of the document in the tab, after X amount of time. 
Currently, X is set to 3000 ms.
I feel this could lead to minor frustrations for users that are reloading the document in less than X amount of time to see changes in the annotation count.

Skip badge request if URL is the cache

---

src/background/browser-action.js
src/background/detect-content-type.js
src/background/hypothesis-chrome-extension.js
src/background/sidebar-injector.js
src/background/tab-state.js
tests/background/browser-action-test.js
tests/background/hypothesis-chrome-extension-test.js
tests/background/tab-state-test.js

Following on from https://github.com/hypothesis/browser-extension/pull/428 this PR fixes issues with and improves the existing JSDoc documentation:
- Fix several JSDoc comments that not start with the correct `/**` text so they are actually parsed as JSDoc
- Convert informal parameter documentation into `@param` so TypeScript can check usage
- Introduce a `@typedef` for the state of each tab so that TS can check usage.
- With the addition of the above typedef, TS can now check that the `state` property (active, inactive, errored) is set to the correct values, so this removes the need for the `states` enum in `tab-state.js`. Since this enum doesn't really have any value any more, I replaced uses of it with equivalent string literals
- Add JSDoc documentation to various methods
In the …

Improve JSDoc for various classes and types in the background page

---

src/unload-client.js

Fix an error about a duplicate `annotatorLink` variable when
de-activating the extension in a tab where it had previously been
active.
It appears that injected scripts all share the same JS global, so if the
`unload-client.js` script is injected multiple times then subsequent
runs would fail due to the `annotatorLink` variable having already been
declared. This didn't happen in the past because the `const` was
transpiled down to `var`, which allows redeclaration. This no longer
happens.
Note that repeatedly activating and re-activating the extension on the same page
is currently broken due to a client issue: https://github.com/hypothesis/client/pull/2782. However, it is possible to reproduce the error on master. It happens when toggling the extension multiple times on the same tab without …

Fix error when deactivating extension a second time in a tab

---

src/background/tab-store.js
tests/background/tab-store-test.js

5 years ago a more flexible, multi-key object was introduced to capture the relevant information about the tabs. The old format, a `"inactive"|"active"` string was retired.
On every extension update the code that runs the conversion is executed. By now, every localStorage is in the new format, therefore this legacy code can safely be retired.

Remove support for old format in the localStorage

---

src/background/hypothesis-chrome-extension.js
src/background/tab-store.js
tests/background/tab-store-test.js

The storage is accumulating information from very old tabs. This is becuase when the extension is restarted it loads all the information in the storage.
This change will enable to load only the information about the current tabs.

Load to memory only information about the current tabs

---

src/background/raven.js
src/tsconfig.json

I believe a recent change in Babel has enabled the import of modules without `default` export.
With those changes if the import was like this:
`import * Raven from 'raven-js`
then functions needed to be invoked like this:
`Raven.default.config` (notice the `default` property)
I enabled `"allowSyntheticDefaultImports": true` in tsconfig.json to match the Babel behaviour.

Fix Sentry problem in production and qa

---

Makefile
src/background/hypothesis-chrome-extension.js
src/pdfjs-init.js
tests/background/hypothesis-chrome-extension-test.js

This PR fixes an issue where a locally-built production extension fails to load, with an error occurring due to a missing `notebookAppUrl` config key in the client boot script. It adds rules to the Makefile to generate a `notebook.html` file and configures the client to set it as the URL of the notebook app.
While this PR fixes an immediate problem, there is a higher-level choice of whether we want the extension to "include" its own Notebook app and show that inside an iframe. We could instead make the "Open notebook" link just open https://hypothes.is/notebook (or equivalent URL depending on the h backend the extension is using) in a new tab. I figure we can merge this now and revisit later if we decide to go down that route.
---
To test locally:
1. Remove any existing install of the …

Add HTML file for notebook app and set `notebookAppUrl` in client config

---

codecov.yml

Added configuration file to prevent spurious codecov notification
warnings resulting from tiny fluctuations

Configure codecov to avoid irrelevant notifications

---

package.json
yarn.lock

This avoids a vulnerability in present in one of the dependencies,
`node-notifier@^8.0.1`.

Update web-ext to the latest version (5.5.0)

---

Jenkinsfile
Makefile
README.md
docs/building.md
gulpfile.js
package.json
src/tsconfig.json
yarn.lock

To facilitate development, `make dev` target has been added. This command
watches the dependency files (via gulp) and builds the browser-extension
when those files are modified.
This new commands support custom setting files: `make dev [SETTING_FILE=custom.js`.
In addition, `make sure` and `make help` targets have been added to make
this project behave similarly to the client project.

Add 'make dev' target to continuously build the extension

---

package.json
src/background/sidebar-injector.js
yarn.lock

Remove a dependency by using `URL.searchParams` to extract a query param from a URL.
This also resolves a theoretical issue where the `originalURL` variable could end up being an array rather than a string if the `file` query param was repeated in the URL, although I don't know of non-contrived scenario (eg. user manually editing URL bar) in which that might happen.

Replace query-string by `URL.searchParams`

---

settings/chrome-dev.json
settings/chrome-prod.json
settings/chrome-qa.json
settings/firefox-dev.json
settings/firefox-prod.json
settings/firefox-qa.json
tools/template-context-app.js
tools/template-context-settings.js

This configuration was used to set the Google Analytics ID used by the
Hypothesis client loaded from the extension. The client no longer uses
GA however.
Related change in h: https://github.com/hypothesis/h/pull/6929

Remove Google Analytics configuration from the extension

---

src/manifest.json.mustache

The Hypothesis client no longer uses Google Analytics, inline JavaScript
(eval) or inline fonts.
The default value of `content_security_policy` would now work, although
we can actually be more strict. The default policy allows additional
script sources (blob, filesystem) which we don't need.

Simplify `content_security_policy` in manifest

---

Makefile
src/pdfjs-init.js
src/pdfjs-setup-env.js
src/pdfjs-worker-init.js
src/vendor/pdfjs/web/viewer.html

Fix loading of the PDF.js viewer (viewer.html) after removing the
unsafe-eval permission from the extension's content security policy.
It turns out that an async/await polyfill (regenerator) in PDF.js's
source bundles relied on this in a fallback code path if assigning a
global `regeneratorRuntime` variable failed:
```js
// Simplified version of code in various PDF.js code bundles
try {
// Code that fails if script is run in "strict" mode and `regeneratorRuntime` is not already defined
regeneratorRuntime = <value>
} catch (...) {
// Fallback code path that relies on `eval`.
new Function('r', 'regeneratorRuntime = r')(<value>)
}
```
Fix the issue by predefining the `regeneratorRuntime` global before
PDF.js loads. We should be able to remove this in future after upgrading
to a release of …

Fix PDF.js viewer failing to load without unsafe-eval

---

Makefile

I added the rule to update the npm libraries before running make
`test|typecheck|format|checkformatting` commands.

Update npm libraries before make commands

---

src/background/sidebar-injector.js
tests/background/sidebar-injector-test.js

This PR is some modernization of `SidebarInjector` and addition of types in preparation for VitalSource-related changes.
There is more to come later, but these changes felt like enough for one PR. See the individual commits for details.
One issue that was raised by the addition of types is that some unusual types ([see notes in Chrome docs](https://developer.chrome.com/docs/extensions/reference/tabs/#type-Tab)) may be missing ID or URL information. I'm not sure if it is possible to actually trigger injection of the client on these tabs, but as of this PR we at least check and throw an error if it is missing.

Modernize and add types to `SidebarInjector`

---

.babelrc
package.json

After the latest PDF.js version update, we require chrome >= 85.  See
https://hypothes-is.slack.com/archives/C1M8NH76X/p1631787431008100
Moved the browser list from .babelrc to package.json

Update the browser version support

---

src/pdfjs-init.js

This removes some code from the pdfjs-init script which is no longer needed with the latest PDF.js and client versions. The revised logic now matches the example code [from the PDF.js wiki](https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage#initialization-promise).
There is a similar version of this code in Via which could also be simplified.
- Remove the `eventBusDispatchToDOM` option, as the client now watches
for these events on the event bus. See [1].
- Use `PDFViewerApplication.initializedPromise` to simplify waiting for
app to load. This was added in PDF.js v2.10.377. See [2].
[1] https://github.com/hypothesis/client/pull/2641
[2] https://github.com/mozilla/pdf.js/pull/11607

Remove obsolete logic from pdfjs-init

---

src/background/browser-action.js
src/background/detect-content-type.js
src/background/direct-link-query.js
src/background/help-page.js
src/background/hypothesis-chrome-extension.js
src/background/sidebar-injector.js
src/background/tab-state.js
src/background/tab-store.js
tests/background/browser-action-test.js
tests/background/detect-content-type-test.js
tests/background/direct-link-query-test.js
tests/background/help-page-test.js
tests/background/hypothesis-chrome-extension-test.js
tests/background/sidebar-injector-test.js
tests/background/tab-state-test.js
tests/background/tab-store-test.js

Per current coding conventions, use named rather than default exports.

Convert default exports to named exports

---

src/background/direct-link-query.js
src/background/errors.js
src/background/hypothesis-chrome-extension.js
src/background/raven.js
src/background/settings.js
src/background/sidebar-injector.js

For the past few months, we have started to use the `object` type instead of `Object`. Both are almost interchangeable, but we prefer `object` for simplicity.
This PR substitutes all `Object` to `object` and makes the code more consistent.
I used these commands (Mac version):
```
% ag -0 -l '@.+Object' | xargs -0 sed -ri '' -e '/@/s/(.*{.*)Object(.*})/\1object\2/'
```

Automatic type substitution of Object for object

---

src/background/chrome-api.js
src/background/sidebar-injector.js
src/manifest.json.mustache
tests/background/chrome-api-test.js
tests/background/sidebar-injector-test.js

**Depends on https://github.com/hypothesis/browser-extension/pull/663**
This PR adds support for loading the client into the VitalSource Bookshelf reader from within the browser extension context.
The initial use case is to make it easier for developers to test the VitalSource integration with various versions of the client (development, QA, production) and without having to go through the LMS app, which complicates the testing environment significantly.
Compared to a regular HTML document, the main difference with loading the client into bookshelf is that we need to target a specific frame which is not the top-level frame in the tab. The current implementation very specifically targets bookshelf, but we could make this more generic. In other words, provide infrastructure in the extension …

Support injecting client into VitalSource Bookshelf

---

src/background/sidebar-injector.js

Simplify async code in SidebarInjector by using async/await to replace
promise chains and `promisify` to convert some callback-accepting Chrome
APIs to Promise-returning functions.

Simplify async code in SidebarInjector

---

src/background/install.js
tests/background/install-test.js

This simplifies the tests by allowing `install.js` to be imported
normally, as the `chrome` fake can be injected before `init` is run.

Eliminate side effects from `install.js` import in tests

---

src/background/help-page.js
src/background/hypothesis-chrome-extension.js
src/background/install.js
tests/background/help-page-test.js

**Depends on https://github.com/hypothesis/browser-extension/pull/663**
The implementation and tests were rather verbose. This commit rewrites HelpPage
to have the same API (at least, the parts that were actually used) and
functionality but a more succinct implementation and tests.
In the process access to the Chrome APIs has been converted to use the
`chrome-api` module and an obsolete code path for old versions of
Firefox was removed.

Refactor HelpPage class

---

tools/deploy

It seems that there is an ongoing problem with either the web-ext tool
or Mozilla's services.
Since we're not actively shipping/supporting the Firefox extension, just
disable signing for the moment.
Example error output from Jenkins:
```
Signing Firefox extensions...
Waiting for Firefox QA signing to complete...
Applying config file: ./package.json
Building web extension from
/data/jenkins/workspace/browser-extension_master/dist/firefox-qa
Validation results:
https://addons.mozilla.org/en-US/developers/upload/1ad32e91ce4f432ba67ba18b554853c5
Error: Signing took too long to complete; last status:
{"guid":"{b441de5f-18e6-40ad-a8c2-f1bd2d42cb01}","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v4/addons/%7Bb441de5f-18e6-40ad-a8c2-f1bd2d42cb01%7D/versions/1.879.0. …
```

Temporarily disable Firefox extension signing

---

README.md
rollup-tests.config.js
tests/karma.config.js
tools/chrome-webstore-refresh-token

We don't use Travis for CI any more.
- Remove references to Travis from README and Karma config
- Remove workaround for Node v14 in Karma config. The problem has been
fixed and Node v16 is currently the LTS version.
- Build and load tests as an ES module. This matches how our other
projects work and eliminates a workaround in the Rollup config

Remove references to Travis and other obsolete test configuration

---

src/background/settings.js

I believe the intention is to strip out the last `/` character, if any
(as the comment say).

Correct regex pattern in the replace

---

src/background/chrome-api.js
src/background/sidebar-injector.js
tests/background/chrome-api-test.js
tests/background/sidebar-injector-test.js

Calls to inject the client into the VitalSource viewer happen in two
ways:
1. Manually, in response to a user activating the extension
2. Automatically, when the browser attempts to re-inject Hypothesis
after a potential navigation ("potential" because the extension
doesn't know if the tab URL changed as a result of a client-side URL
update or a server-side page change).
In scenario (2) the tab would always be flagged as having an error
because the `chrome.permissions.request` API fails if called outside of
a user gesture, even if the extension already has the permission.
Fix the issue by checking for the permission using
`chrome.permissions.getAll`, which does not require a user gesture, and
then only requesting if if needed.
---
**Testing:**
Only a book in VitalSource on this branch and …

Don't request "webNavigation" permission if we already have it

---

src/background/chrome-api.js
src/background/sidebar-injector.js
tests/background/chrome-api-test.js
tests/background/sidebar-injector-test.js

One of the major changes between Manifest V2 and Manifest V3 is the API for executing scripts in a tab. Add `executeFunction` and `executeScript` wrappers in `chrome-api.js` which wrap the extension APIs for script execution provided by the current browser. Currently this calls the `chrome.tabs.executeScript` API from Manifest V2 / WebExtensions. In future it will call `chrome.scripting.executeScript` in browsers that support Manifest V3.
As well as abstracting over browser differences, these wrappers also enable better typing and a simpler interface for other parts of the extension. The Manifest V3 APIs for executing a script or function in a tab are, in particular, a bit cumbersome because they supports multiple files and frame IDs even though we only ever pass one, and the `tabId` …

Add wrappers around extension APIs for executing scripts

---

settings/chrome-dev.json
settings/chrome-prod.json
settings/chrome-qa.json
settings/firefox-dev.json
settings/firefox-prod.json
settings/firefox-qa.json
tools/template-context-app.js

The client now obtains this URL from the `/api/links` endpoint.  See https://github.com/hypothesis/h/pull/7254 and
https://github.com/hypothesis/client/pull/4148.
This should not be merged until https://github.com/hypothesis/client/pull/4148 is deployed. (_Update: This is now done._)

Remove `websocketUrl` setting

---

.prettierignore
Makefile
tools/template-context-app.js

Change the Prettier config to format all JS files except for ignored
directories. This ensures that all files in the root dir and tools/ are
formatted.

Format JS files in tools/ folder

---

.github/dependabot.yml

The extension no longer uses this package.

Remove obsolete Dependabot config

---

.gitignore
docs/building.md

Grabbing at anything that makes the local-build workflow even incrementally easier for devs...
For ease of development workflow, ignore any JSON settings files with "custom" in the filename.

Don't track custom settings JSON

---

Jenkinsfile
README.md

As part of this work, references to master have been replaced with main
in:
1. README.md
2. Jenkinsfile

Default branch renamed to main

---

.eslintrc
package.json
yarn.lock

The newest eslint-config-hypothesis assumes the use of Prettier, so the
override is not needed.

Update ESLint config, remove obsolete override

---

.github/workflows/continuous-integration.yml

The git-describe npm package, which is used by tools/settings.js to generate a version number, defaults to enabling this flag. Without it only annotated tags are considered, and none of the recently created tags are annotated. Hence to get the build logs to display a version number that matches what is in the built packages, we need to add this flag.

Add `--tags` argument to `git describe`

---

.github/workflows/update-client.yml
tools/update-client

The plan is for this workflow and script to be triggered at the end of a new Hypothesis client release, in order to automatically update the browser extension. This matches functionality that was previously implemented in the client/extension's Jenkins build pipelines.

Add script and GitHub Actions workflow to update client

---

.github/workflows/update-client.yml

This fixes two issues with the workflow for updating the Hypothesis client:
1. The job name was wrong
2. We need to set a Git identity in order to create a commit
I think there will be some additional steps to work around a restriction that pushes triggered by GitHub Actions cannot trigger other workflows. See https://stackoverflow.com/questions/57921401. I will look into this tomorrow.

Update git identity in "Update client" workflow

---

.github/workflows/release.yml
.github/workflows/update-client.yml

The update-client workflow pushes a commit and tag to main. This would normally trigger the release workflow in turn. This doesn't happen because events triggered by workflows cannot trigger other workflows (since comments), so trigger this workflow manually after the client is updated.

Run release job "manually" after client update

---

.github/workflows/update-client.yml

Without this, uploads to the Chrome web store will fail due to missing secrets.

Inherit secrets when calling release workflow from update-client

---

.github/workflows/release.yml
.github/workflows/update-client.yml

When running the release workflow after updating the client, make sure that the new tag created by the update-client workflow is checked out, instead of the previous commit that was at the tip of the main branch when the update-client workflow was initiated.

Check out new tag when releasing updated client

---

.github/workflows/update-client.yml

Fix the syntax of the set-output command to match the examples in the docs. See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter.

Fix set-output syntax

---

.github/workflows/continuous-integration.yml
.github/workflows/release.yml

When the update-client workflow runs the release workflow, it passes the new ref created after the Hypothesis client package is updated. The release workflow was using this ref when running the release scripts, but not when calling the continuous-integration workflow to actually build the client. Hence the built client ended up with the wrong version number. Fix this so that the new ref is passed from update-client to release and then to the continuous-integration workflow.

Pass ref from release workflow to CI workflow

---

package.json
tests/karma.config.js
yarn.lock

Remove Puppeteer and use the system version of Chrome, for the same reason as in the client project. See https://github.com/hypothesis/client/pull/4945.

Remove Puppeteer

---

.babelrc
.eslintrc
package.json
rollup-tests.config.mjs
rollup.config.mjs
src/background/uri-info.ts
tests/bootstrap.js
tests/promise-util.js
tests/util.js
tools/.eslintrc
yarn.lock

This includes the same core changes as https://github.com/hypothesis/client/pull/4725. Additionally:
- Some remaining test modules with CommonJS exports and "use strict" at the top were converted to ES modules
- uri-info.js has been converted to TS as a test case
Unlike other projects, the browser extension has a number of small entry point scripts which are still loaded as scripts rather than ES modules. These are allow-listed in .eslintrc.

Support native TypeScript modules

---

.github/workflows/continuous-integration.yml
.github/workflows/release.yml
.github/workflows/update-client.yml

This pull request addresses a couple of warnings printed in our workflows, by updating to the latest instances of some actions and changing how we pass info between jobs via output.

Update GitHub actions dependencies

---

Makefile
src/background/extension.js
tests/background/extension-test.js

Like the corresponding route in h (https://github.com/hypothesis/h/pull/7817), this is the same as the sidebar HTML.
We probably want to revisit how these URLs are configured soon, so that we don't need separate files and `<link>` elements for each sidebar-like app in the client. This change unblocks deployments of the extension though. Without this the extension fails to start.
I also removed an obsolete notice about a Chrome bug, which has now been resolved.

Add profile app HTML to extension

---

src/manifest.json.mustache

This is a prerequisite for publishing the extension as a Manifest V3 extension.
Chrome 88 was published in Jan 2021, so > 2 years old at this point. There are some MV3 APIs that require a newer version of Chrome than 88, but I haven't found a need for them yet.
Part of #622

Bump minimum Chrome version to 88

---

src/background/extension.js
src/pdfjs-init.js

The `profileAppUrl` setting was added to `src/background/extension.js` but not mirrored in `pdfjs-init.js`. This caused the wrong profile app URL to be used when viewing a PDF. It also lead to a cryptic error from the client's `processUrlTemplate` function when testing with a PDF and a local build of the client, due to `processUrlTemplate` not being able to handle `chrome-extension://` URLs properly.
In future it would be ideal if the `pdjs-init.js` script could share its config object definition with `src/background/extension.js`. Currently however it isn't easy to share code between the two files. It would also be nice to eliminate the need to specify an entry point for a multitude of mini-apps (sidebar, notebook, profile) that constitute the client. That's left as an exercise for the …

Sync client config in PDF.js with config for web pages

---

src/background/sidebar-injector.js
src/pdfjs-init.js

Closes #1180 
By adding `data-remove-on-unload` attribute to the config script, we ensure the client removes that script when unloaded, which happens when the extension is inactive.
In order to test it, build the dev extension on this branch, and see how the `js-hypothesis-config` script tag gets removed when the extension is deactivated.

Add `data-remove-on-unload` on config script so that it gets removed when the extension is deactivated

---

src/background/sidebar-injector.js
tests/background/sidebar-injector-test.js

Small refactor brought from https://github.com/hypothesis/browser-extension/pull/1193, which was not merged, but it introduced 2 changes that I think are worth keeping:
- Make `injectIntoHTML` implicitly call `injectConfig`, making it consistent with `injectIntoVitalSourceReader`.
- Wrap the execution of the client's boot script into its own reusable function.

Refactor sidebar-injector to remove duplication

---

src/background/chrome-api.js
src/background/settings.js
src/background/tab-state.js
src/manifest.json.mustache

This PR enables the extension to be built as a Manifest V3 extension by setting the `manifestV3` key to `true` in the settings JSON.
Part of https://github.com/hypothesis/browser-extension/issues/622.
**Summary of changes:**
- Add conditionals in `manifest.json` to build extension for Manifest V3
- Use MV3 APIs for executing scripts (files or functions) in the page when building for Manifest V3
**Testing:**
1. Add `"manifestV3": true` to the settings JSON file you use for development, and build the extension
2. Build the extension and load it in Chrome.
3. Go to the extension's info page under chrome://extension and under "Inspect views" you should see that it displays "Service worker" instead of background page
Example of my local Chrome settings JSON:
```json
{
"buildType": "dev", …
```

Support building extension for Manifest V3

---

src/background/extension.js
src/background/sidebar-injector.js
src/help/index.html
tests/background/extension-test.js
tests/background/sidebar-injector-test.js

Work around an issue in Manifest V3 where async calls in-between a user clicking an extension's toolbar action and attempting to request additional permissions results in an error "The function must be called during a user gesture" when calling `chrome.permissions.request` [1]. In our context this happens when activating Hypothesis on a https://bookshelf.vitalsource.com URL.
The workaround is to request any additional permissions that might be required, based on the tab's URL, immediately after clicking the toolbar action. This workaround relies on us being able to determine what permissions may be needed based on the URL alone, which is currently the case.
In an additional commit I also fixed an issue where error messages of > 60 chars would overflow their container on the extension …

Request `webNavigation` permission directly after clicking browser action

---

settings/chrome-dev.json
settings/chrome-prod.json
settings/chrome-qa.json

~~**Depends on https://github.com/hypothesis/browser-extension/pull/1031, https://github.com/hypothesis/browser-extension/pull/1195.**~~
Switch the dev, QA and prod Chrome extensions to Manifest V3 by default. See [Slack thread](https://hypothes-is.slack.com/archives/C1M8NH76X/p1681394873609259) for rollout discussion.
Part of https://github.com/hypothesis/browser-extension/issues/622.
**Testing:**
1. Remove the QA and prod Hypothesis extensions, if you have them installed. Also remove any existing local Hypothesis extension.
2. Build the QA extension locally using `make build SETTINGS_FILE=settings/chrome-qa.json` and test it
3. Remove the QA extension from Chrome
4. Build the prod extension locally using `make build SETTINGS_FILE=settings/chrome-prod.json` and test it

Enable Manifest V3 by default

---

src/background/chrome-api.js
src/background/sidebar-injector.js
tests/background/chrome-api-test.js
tests/background/sidebar-injector-test.js

This PR changes the logic to generate the config script so that it adds an attribute with the ID of the extension that generated it.
This way, the client boot script can then check if there's a config generated by an extension, and which extension specifically, and more granularly determine if it was executed by that extension or not.
For more info, see https://github.com/hypothesis/client/pull/5392#discussion_r1168488629
1. Checkout this branch.
2. Build the browser extension: `make build SETTINGS_FILE=settings/<custom>.json`
3. Load built extension into Chrome.
4. Activate the extension, and verify it has the new `data` attribute with the extension ID.

Inject extension id as an attribute on generated config

---

src/background/chrome-api.ts
src/background/detect-content-type.ts

This converts the remaining "useful" modules in src/background to TypeScript. There is one remaining module, `raven.js`, but that is an old Sentry integration ("raven" was the name of the old Sentry JS client library) that is not currently active. The chrome-api.ts module can be simplified significantly once we finalize the Manifest V3 migration by removing all Manifest V2-related code. I don't want to commit to that until the MV3 extension has been released to production and in use for a few weeks though.

Convert src/background/{chrome-api.js, detect-content-type.js} to TypeScript

---

Makefile
src/background/chrome-api.ts
src/background/detect-content-type.ts
src/background/sidebar-injector.ts
src/pdfjs-init.js
tests/background/sidebar-injector-test.js

Previously the Hypothesis client config passed to
`SidebarInjector.injectIntoTab` was not used when activating the client in a
PDF. Instead the client used static configuration from pdfjs-init.js. This
caused several problems:
- When modifying the client config in extension.ts, the developer had to
remember to update it in pdfjs-init.js separately (see
96c1dca03492c8e44573d4366a449050d898b3cd for an example of this being
forgotten).
- There was no nice mechanism available to pass dynamic configuration to the
client for PDF documents.
- Passing of direct link query information from the extension to the client
worked differently in PDFs than HTML documents. This resulted in direct links
for PDFs breaking after 3df9fc0ba8f4f1c02f2a004a86390d81c458c282.
This commit resolves the issue by using …

Pass same client configuration to PDFs as for other document types

---

.eslintrc
src/background/browser-action.ts
src/background/extension.ts
src/background/raven.js
src/background/tab-state.ts
src/help/index.js
src/options/options.js
tests/background/browser-action-test.js
tests/background/detect-content-type-test.js
tests/background/errors-test.js
tests/background/extension-test.js
tests/background/help-page-test.js
tests/background/sidebar-injector-test.js
tests/promise-util.js
tests/util.js

This PR contains two general code style modernization updates.
- The first commit refactors the function that loads/unloads the client into tabs to use async / await, and also gives it a more obvious name
- The second commit enables the ESLint functions to prefer arrow functions over un-named `function`s (named functions are still allowed) and prefer object shorthand syntax over `foo: foo`. These lint rules are already enabled in client code.

Modernize code using async/await, object shorthand syntax and arrow functions

---

tools/update-client

`yarn add hypothesis@latest` sets the version range for the "hypothesis" dependency in package.json to "latest", instead of resolving it to a semver. Consequently the regex to parse the version number failed to match.
`yarn add <dep>` generates a semver range for the `latest` tag by default, so just use that.

Fix tools/update-client for Yarn v3

---

README.md

The use of [`yarn link`](https://yarnpkg.com/cli/link) changed after the upgrade to Yarn v3+. It is no longer necessary to run `yarn link` in the client repository. Instead you can just do `yarn link ../path/to/client` in the browser extension repository.
`yarn unlink` still accepts a package name, so `yarn unlink hypothesis` still works. However the docs mention that you can also specify the path instead: https://yarnpkg.com/cli/unlink (ie. `yarn unlink ../client`).
Fixes https://github.com/hypothesis/browser-extension/issues/1404

Update `yarn link` instructions for Yarn v3+

---

.github/workflows/continuous-integration.yml
settings/chrome-staging.json
settings/firefox-staging.json
src/background/browser-action.ts
src/background/sidebar-injector.ts
tests/background/browser-action-test.js
tests/background/sidebar-injector-test.js
tools/deploy

Update the browser extension following the replacement of qa.hypothes.is with staging.hypothes.is.
New auth clients have been registered at https://staging.hypothes.is/admin/oauthclients.
**Testing:**
1. Remove Hypothesis QA/staging extension if already installed
2. Build local staging extension:
```
make build SETTINGS_FILE=settings/chrome-staging.json
```
3. Load extension in Chrome and verify that you can log in and annotate
The extension now displays the letters "STG" rather than "QA" on the badge.

Update configuration for QA/staging extension

---

.github/workflows/continuous-integration.yml
.github/workflows/release.yml
.github/workflows/update-client.yml

This should resolve warnings about use of deprecated Node 16 in workflows.
See also https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Update GitHub Actions workflows

---

.eslintrc
src/help/index.html
src/help/index.js
src/options/index.html
src/options/options.js
src/pdfjs-init.js
src/vendor/pdfjs/web/viewer.html

Load the JS for the help, options and PDF viewer pages as modules. This makes handling of the code more consistent with the background service worker, which is written as ES modules and bundled into a script.
This PR is a small piece of cleanup prior to a future ESLint v9 upgrade.

Load scripts as modules where possible

---

src/background/chrome-api.ts
src/background/detect-content-type.ts
tests/background/detect-content-type-test.js

Fix detection of document type in Chrome's built-in PDF viewer when the "OOPIF
for PDF Viewer" feature ("pdf-oopif") is enabled.
Fixes https://github.com/hypothesis/support/issues/145
Related upstream issue tracking launch of this Chrome change: https://issuetracker.google.com/issues/40268279
----
**Testing:**
1. In Chrome, go to chrome://flags and enable the "OOPIF PDF viewer" experiment.
2. Restart your browser
3. Build extension on main, navigate to https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf and attempt to activate the extension. It should fail to activate.
4. Check out this branch and repeat step (3). The PDF viewer should work as normal.
5. Disable the "OOPIF PDF viewer" experiment in Chrome, restart the browser and very that this branch still works with …

Support OOPIF PDF viewer in Chrome

---

Makefile
src/background/chrome-api.ts
tests/background/chrome-api-test.js

Since the migration to Manifest V3 is now complete, all of the `chrome` APIs support returning promises, so we don't need to wrap the older callback-returning APIs to return promises. This simplifies the code and also removes the need for a TypeScript workaround when resolving the type of wrapped functions.
In the process I had to fix an error when running `make format` locally due to `node_modules/.bin/prettier` not being executable. This had been on my TODO list for a while.

Simplify Chrome API wrapper

---

.github/dependabot.yml

Since we [migrated to ESLint 9](https://github.com/hypothesis/browser-extension/pull/1617/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L22-L23), no longer depend on `@typescript-eslint/...` packages directly, but on the `typescript-eslint` package instead.
This PR updates the dependabot eslint group to reflect that.

Add typescript-eslint to eslint dependabot package

---

src/background/chrome-api.ts
src/background/index.ts
tests/background/index-test.js

Fixes https://github.com/hypothesis/product-backlog/issues/1599
**Testing:**
1. Build and install development extension
2. Uninstall the extension
3. Chrome should open a new tab at [this URL](https://docs.google.com/forms/d/e/1FAIpQLSd250Bi4xvxxvL-SgajHRmk8K1LMLZLGRoYkp6WSwT8PDTlLA/viewform)

Show survey to users after extension is uninstalled

---

package.json
rollup-tests.config.js
src/background/index.ts
yarn.lock

The `process` variable does not exist at all when the background script is loaded in Chrome normally. Resolve this in a similar way to the @hypothesis/lms repo [^1] by defining a variable using @rollup/plugin-replace instead.
Using `process.env.NODE_ENV` works in some of our other projects because they use @rollup/plugin-replace to replace it at build time. This is non-obvious from looking at the code however, so I think we should probably use a more-obvious custom variable.
[^1]: https://github.com/hypothesis/lms/blob/bc01ef9b7015b4c460250bf65b311b014e17368f/rollup-tests.config.js#L44

Fix reference to undefined `process` variable when loading extension

---

.github/workflows/release.yml
.github/workflows/update-client.yml

Remove the workflow steps that automatically automatically build and upload the QA and production extensions after commits to main. The release fails if there is a draft extension in the pending review state when an extension is uploaded. This has been happening frequently in recent weeks due to reviews in the Chrome Web Store having become much slower, for both the QA and production extension. Previously reviews would often happen in 30 minutes or so, but now sometimes take several days. Hence automated releases frequently failed.
Instead switch to a process where extension releases are triggered manually:
1. Go to the Chrome Web Store and verify that the QA and production extensions are both released and not in a pending-review state. If either is in a pending review state, either wait …

Disable automatic upload of extension after commits to main

---

.github/dependabot.yml

Add the same "vitest" group that exists in the hypothesis/client repo. This ensures that the vitest sub-packages are updated together. Mixing different versions of `@vitest/browser` and `vitest` for example caused a failure in https://github.com/hypothesis/browser-extension/actions/runs/14974780002/job/42064210348?pr=1738.

Add vitest Dependabot group

---

Makefile
tools/render-boot-template.js

When packaging the Hypothesis client for inclusion in the extension, replace the boot script containing cdn.hypothes.is URLs with one that references client-bundled URLs via `chrome.runtime.getURL`. We still set `assetRoot` and related URLs in order to support annotation-enabled same-origin iframes, so the new URLs are not actually used. Importantly however, the remote CDN URLs no longer appear in the bundle. This avoids giving the mistaken impression that we were loading remote code.
See https://github.com/hypothesis/client/pull/7099.
CI will fail until the client is updated to include https://github.com/hypothesis/client/pull/7099.

Remove references to cdn.hypothes.is from boot script
